// Eleven nurturing, non-clinical self-assessments for veterans.
// These are reflective check-ins, not medical diagnostics. Each one returns a
// gentle 4-tier reading + a next step + a relevant resource.

export const ASSESSMENTS = [
  {
    id: 'transition-readiness',
    title: 'Transition Readiness Check-In',
    sub: 'A 6-question reflection on where you actually are in the shift from service to civilian life.',
    icon: 'compass',
    questions: [
      'I have a clear written picture of what my next chapter looks like (work, money, health, relationships).',
      'I know what I am bringing forward from service that I am proud of.',
      'I know what I am ready to leave behind.',
      'I have at least three people I can be honest with.',
      'I sleep at least six unbroken hours most nights.',
      'I have a daily anchor — a habit, walk, or ritual — that grounds me.',
    ],
  },
  {
    id: 'sleep',
    title: 'Sleep & Nervous-System Check-In',
    sub: 'Six gentle questions to surface whether your sleep is repairing you or eroding you.',
    icon: 'moon',
    questions: [
      'I fall asleep within 30 minutes most nights.',
      'I wake up feeling rested at least four mornings a week.',
      'I sleep through the night without a 2–4am wake-up loop.',
      'I do not need alcohol or screens to fall asleep.',
      'My partner and I both sleep without disturbing each other.',
      'I dream and remember dreams at least once a week.',
    ],
  },
  {
    id: 'mood',
    title: 'Mood & Meaning Check-In',
    sub: 'How heavy or light is your inner weather right now?',
    icon: 'sun',
    questions: [
      'I feel curious about something most days.',
      'I look forward to small moments, not just big events.',
      'I laugh — really laugh — at least a few times a week.',
      'I feel a sense of meaning in how I spend my days.',
      'My anger is in proportion to what is in front of me.',
      'I can name what I am feeling without effort.',
    ],
  },
  {
    id: 'relationships',
    title: 'Relationships & Family Check-In',
    sub: 'A look at the people closest to you — and how present you actually are with them.',
    icon: 'heart',
    questions: [
      'My partner and I have one real, slow conversation each week.',
      'I know my kids\u2019 best friends and the names of their teachers.',
      'I have at least one friend I see in person each month.',
      'I can ask for help without it feeling like weakness.',
      'I am not numbing through alcohol, screens, or work.',
      'I have repaired the last thing I broke with someone I love.',
    ],
  },
  {
    id: 'career',
    title: 'Career Direction Check-In',
    sub: 'Where you are in the work-after-service decision tree.',
    icon: 'briefcase',
    questions: [
      'I have written down what I want my work to give me beyond a paycheck.',
      'I have a current civilian-style résumé I am proud of.',
      'I have spoken to three people in fields I am considering.',
      'I have a 6-month financial runway or a clear plan to one.',
      'I know whether I want to lead, build, or serve in this next chapter.',
      'I can describe my work in plain English without acronyms.',
    ],
  },
  {
    id: 'va-benefits',
    title: 'VA Benefits Awareness Check-In',
    sub: 'Are you using what you earned, or leaving the door closed?',
    icon: 'flag',
    questions: [
      'I am enrolled in VA healthcare or have actively chosen not to be.',
      'I have a current disability rating or know exactly how to file.',
      'I know the difference between Post-9/11 and Montgomery GI Bill.',
      'I have a primary VSO (DAV, VFW, AL, MOPH) I trust.',
      'I have my DD-214 and benefits letter saved in two places.',
      'I know what my BAH-equivalent housing stipend would be if I went back to school.',
    ],
  },
  {
    id: 'finances',
    title: 'Money & Stability Check-In',
    sub: 'Six honest questions about the money under your transition.',
    icon: 'wallet',
    questions: [
      'I know what I spend in an average month within ±$200.',
      'I have at least one month of expenses set aside in cash.',
      'I am not carrying credit card debt above $5,000.',
      'I am contributing to a retirement account at least monthly.',
      'My partner and I look at the numbers together at least monthly.',
      'I have life insurance and a basic will.',
    ],
  },
  {
    id: 'physical',
    title: 'Physical Body Check-In',
    sub: 'Is your body the foundation under your next decade, or is it the bottleneck?',
    icon: 'activity',
    questions: [
      'I move my body for 30+ minutes at least four days a week.',
      'I can carry groceries up two flights without losing breath.',
      'My weight is within 10 pounds of where I want it to be.',
      'I have had a full physical in the last 12 months.',
      'I drink less than 8 alcoholic drinks a week.',
      'I am not in chronic pain that I am ignoring.',
    ],
  },
  {
    id: 'spiritual',
    title: 'Meaning & Spiritual Check-In',
    sub: 'A non-religious read on whether your inner life has weight again.',
    icon: 'star',
    questions: [
      'I have a daily or weekly practice that quiets my mind.',
      'I feel connected to something larger than myself.',
      'I can sit with silence for 15 minutes without restlessness.',
      'I grieve the losses I have actually had, instead of bypassing them.',
      'I know what I would tell a younger version of myself.',
      'I feel grateful at least once a day, on purpose.',
    ],
  },
  {
    id: 'community',
    title: 'Community & Brotherhood Check-In',
    sub: 'How woven are you into a fabric of people who actually know you?',
    icon: 'users',
    questions: [
      'I have at least one veteran I check in with monthly.',
      'I am part of a group, team, or community that meets in person.',
      'I have helped someone else this month without keeping score.',
      'I know my neighbors\u2019 names — at least three of them.',
      'I have a mentor or someone older I learn from.',
      'I am someone\u2019s mentor, even informally.',
    ],
  },
  {
    id: 'identity',
    title: 'Identity Beyond the Uniform',
    sub: 'A reflection on who you are now, without the rank.',
    icon: 'shield',
    questions: [
      'I can describe myself without leading with my service record.',
      'I have hobbies that have nothing to do with the military.',
      'I do not feel like I have to perform a "veteran" version of myself.',
      'I have new friends from the last five years.',
      'I have grown in ways I am proud of since separating.',
      'I see my service as a chapter, not the whole book.',
    ],
  },
];
