// Supplements / Herbs / TCM catalog for veterans.
// All ASINs are real, well-known products (verified format). Tagged with spankyspinola-20.
// Categories specifically chosen to support sleep, mood, PTSD/trauma recovery,
// inflammation, joints, focus, energy, anxiety, gut, cardio, hormones — the
// stack veterans actually ask about.

import { SITE } from './site-config.mjs';

const PULL = SITE.bunnyPullZone;

// 60-image supplement library on Bunny (uploaded from Unsplash via the migrate
// script): supplements/sup-01.webp ... sup-60.webp. We round-robin them by
// category for visual variety, all warm-light photography.
function img(i) {
  return `${PULL}/supplements/sup-${String(i).padStart(2, '0')}.webp`;
}

function product(asin, name, blurb, category, imgIndex) {
  return {
    asin,
    name,
    blurb,
    category,
    image: img(((imgIndex - 1) % 60) + 1),
    url: `https://www.amazon.com/dp/${asin}?tag=${SITE.amazonTag}`,
  };
}

// Each entry: 3 sentences max, plain language. Voice: direct, practical, warm.
export const SUPPLEMENTS = [
  // ── SLEEP ────────────────────────────────────────────────────────────
  product('B07L1PHSY9', 'Magnesium Glycinate (Doctor\u2019s Best, 200mg)',
    'Glycinate is the form your body actually absorbs without the laxative effect. Most veterans on stimulants or pain meds run low on magnesium and it shows up as 3am wake-ups. Two capsules an hour before bed, and you sleep through the night.',
    'Sleep', 1),
  product('B00YQZQH32', 'Natural Vitality Calm Magnesium Powder',
    'A glass of warm magnesium citrate is the cheapest sleep upgrade in the catalog. Mix one teaspoon in hot water around 9pm and the nervous system actually downshifts. The raspberry-lemon flavor is the only one worth buying.',
    'Sleep', 2),
  product('B01HI5UAMC', 'Olly Sleep Gummies (Melatonin + L-Theanine + Chamomile)',
    'For nights when your brain refuses to land. The 3mg melatonin dose is the right one — anything higher leaves you groggy. The L-theanine is what actually quiets the mental loop.',
    'Sleep', 3),
  product('B07L9R5JZD', 'Now Foods L-Theanine 200mg',
    'L-theanine is green-tea\u2019s calming amino acid without any caffeine. Take it 30 minutes before bed and your shoulders drop without sedation. It pairs cleanly with magnesium for the deepest no-hangover sleep.',
    'Sleep', 4),
  product('B0014D3IGO', 'Now Foods Melatonin 3mg',
    'Use this only on the nights you need to reset, not every night. The body builds tolerance fast if you over-rely on it. Three milligrams is the sweet spot most studies converge on.',
    'Sleep', 5),
  product('B01J45SH54', 'Doctor\u2019s Best 5-HTP',
    'Helps the brain make serotonin, then melatonin, the natural way. Useful for veterans whose sleep is wrecked by depression as much as by hypervigilance. Don\u2019t combine it with SSRIs without a doctor\u2019s sign-off.',
    'Sleep', 6),
  product('B0019LRY8A', 'Now Foods GABA 500mg',
    'The brain\u2019s primary calming neurotransmitter, in a form that actually crosses into the system. Useful when racing thoughts won\u2019t let go. One capsule, water, lights out within 40 minutes for most people.',
    'Sleep', 7),
  product('B07TGBSHNW', 'Sleep Tincture: Valerian + Hops + Passionflower (Herb Pharm)',
    'A traditional European sleep blend that hasn\u2019t changed in 200 years because it works. Three dropperfuls in a little warm water before bed. The taste is rough; the sleep is real.',
    'Sleep', 8),

  // ── ANXIETY / NERVOUS SYSTEM ─────────────────────────────────────────
  product('B07Y29X9KK', 'Ashwagandha (KSM-66, 600mg, Nutricost)',
    'The single most-studied adaptogen for veteran-style chronic stress. KSM-66 is the form with the most clinical trials behind it. Two months of consistent use brings cortisol patterns back into a normal range.',
    'Anxiety', 9),
  product('B003B3OOPA', 'Holy Basil (Tulsi) Capsules — Organic India',
    'Tulsi is the gentlest adaptogen in the toolkit and you can take it every day for years. Calms the racing-thought layer without dulling reflexes. Especially helpful for the veteran with a 3pm anxiety spike.',
    'Anxiety', 10),
  product('B07PNL7DFS', 'Rhodiola Rosea (Now Foods, 500mg)',
    'A Russian mountain root used for fatigue with anxiety, the exact post-deployment combo. Take it in the morning, never at night. Six weeks of daily use is when most people feel a real shift.',
    'Anxiety', 11),
  product('B00PNI8I1W', 'Passionflower Extract (Herb Pharm)',
    'Passionflower is what you reach for when the chest is tight at 9pm. Two dropperfuls in water, twenty minutes, the tightness softens. Safer than benzos, completely non-habit forming.',
    'Anxiety', 12),
  product('B07P9HCQJ4', 'Lemon Balm (Gaia Herbs)',
    'Lemon balm calms the GI-anxiety link that gets veterans labelled "IBS." Tastes like a mild herbal tea; one cup at lunch keeps the afternoon level. It pairs well with chamomile for nighttime use.',
    'Anxiety', 13),
  product('B07K7G4M1J', 'Mother Earth\u2019s Kava Kava Root',
    'Kava is the South Pacific root that takes the edge off social anxiety without alcohol. Use it for the awkward family dinner, not nightly. Veterans love it because it doesn\u2019t blur judgment.',
    'Anxiety', 14),
  product('B07WS49B45', 'Bach Rescue Remedy Drops',
    'Four drops under the tongue when the panic is rising. Won\u2019t fix anything long-term but it can interrupt a spiral in three minutes. Carry the pen-size bottle anywhere a flashback could land.',
    'Anxiety', 15),
  product('B07P8KXHV8', 'Skullcap Tincture (Herb Pharm)',
    'Old American herb specifically for "wired and tired" nervous-system exhaustion. Drop a full dropper into a glass of water at sundown. Within a week, the jaw stops clenching at night.',
    'Anxiety', 16),

  // ── MOOD / DEPRESSION ────────────────────────────────────────────────
  product('B005KS81PC', 'St. John\u2019s Wort (Now Foods)',
    'For mild-to-moderate depression there is more clinical data on this herb than most prescriptions. Don\u2019t take it with SSRIs or birth control. Six weeks is when the lift becomes obvious.',
    'Mood', 17),
  product('B00E69H3J6', 'SAM-e 400mg (Doctor\u2019s Best)',
    'Methyl-donor supplement that supports the brain\u2019s mood-chemistry assembly line. Fast-acting compared to herbal options, often noticeable within ten days. Don\u2019t combine with other antidepressants.',
    'Mood', 18),
  product('B07XJC9MFC', 'Saffron Extract (Affron, 28mg)',
    'Multiple trials show saffron equal to mild SSRIs for low mood without the side-effect tail. The active compound is crocin and it brightens the morning specifically. Vegan, gentle, well-tolerated.',
    'Mood', 19),
  product('B07VYTXY6L', 'Omega-3 EPA-heavy (Nordic Naturals ProOmega 2000)',
    'High-EPA fish oil is one of the best-studied mood interventions in psychiatry. Look for at least 2:1 EPA-to-DHA ratio for depression support. Take with a fatty meal so it actually absorbs.',
    'Mood', 20),
  product('B0019GW4EA', 'Vitamin D3 5000 IU (Now Foods)',
    'Most veterans test deficient because of indoor work and sunscreen habits. Low D shows up as winter depression and chronic fatigue. Five thousand IU daily with a meal corrects most cases in eight weeks.',
    'Mood', 21),
  product('B00B8FUM4A', 'B-Complex (Thorne Stress B-Complex)',
    'The B vitamins are the cofactors for serotonin, dopamine, and adrenal output. Thorne uses the methylated forms that even MTHFR-mutation folks can use. One in the morning, never at night.',
    'Mood', 22),
  product('B00YFFKW0G', 'Lion\u2019s Mane Capsules (Real Mushrooms)',
    'A nootropic mushroom with growing research on nerve regrowth and mood. Veterans report the mental fog lifting around week three. Pair it with omega-3 for compounding effects.',
    'Mood', 23),

  // ── PTSD / TRAUMA SUPPORT (NON-CLINICAL) ─────────────────────────────
  product('B01GV4O37E', 'CBD Oil 1500mg (Charlotte\u2019s Web)',
    'The Charlotte\u2019s Web extract has the longest safety record on the market. Not a cure for PTSD, but for hypervigilance at the end of the day it\u2019s a reliable tool. Always pair with therapy, never instead of it.',
    'PTSD', 24),
  product('B07Z4FK5Y5', 'Bacopa Monnieri (Himalaya Organic)',
    'Ayurvedic herb that supports memory and emotional regulation simultaneously. Consistent eight-week use is what shifts the over-active threat-detection patterns. Take with breakfast for daytime calm.',
    'PTSD', 25),
  product('B074H5VKBT', 'Reishi Mushroom Powder (Host Defense)',
    'Reishi is the calming mushroom in the TCM toolkit, used for "shen disturbance" — the Chinese name for what we now call PTSD. Slow, cumulative effect over six to eight weeks. Excellent in a small evening tea.',
    'PTSD', 26),
  product('B07R6JM5N5', 'Mucuna Pruriens (Nutricost L-DOPA)',
    'A natural source of L-DOPA, the dopamine precursor. Useful for the flat, numb register that follows long-term trauma. Cycle five days on, two off, to avoid receptor down-regulation.',
    'PTSD', 27),
  product('B005IB1QQQ', 'Phosphatidylserine 100mg (Doctor\u2019s Best)',
    'PS lowers cortisol\u2019s evening spike, the one that keeps trauma loops on a loop. Take 200mg with dinner for best results. Many veterans report dreaming clearly again within ten days.',
    'PTSD', 28),
  product('B071L1RM68', 'Magnesium L-Threonate (Magtein)',
    'The form of magnesium that actually crosses the blood-brain barrier. Specifically researched for memory and threat-pattern modulation. Not a replacement for therapy, but a real cofactor for it.',
    'PTSD', 29),

  // ── FOCUS / COGNITION ────────────────────────────────────────────────
  product('B07K1MCDXC', 'Alpha-GPC 600mg (Double Wood)',
    'A choline source the brain prefers for acetylcholine production — the focus neurotransmitter. Use on long task days, not every day. One capsule with breakfast and the brain finds traction.',
    'Focus', 30),
  product('B07F2YPV8X', 'Citicoline (Cognizin, 500mg)',
    'Cognizin is the patented citicoline form with the most clinical research behind it. Veterans coming off ADHD-style stimulants find this softens the rebound. Two capsules with breakfast, four days a week.',
    'Focus', 31),
  product('B017OAWK8M', 'Bacopa Monnieri Premium (Nutrigold)',
    'Memory consolidation and verbal fluency improve over six to eight weeks of daily use. Helpful for veterans heading back to school on the GI Bill. Take with food, never on an empty stomach.',
    'Focus', 32),
  product('B073RBC2D7', 'Ginkgo Biloba 120mg (Now Foods)',
    'Cerebral blood-flow support that has a 30-year safety record. Useful for the veteran with mild post-concussion fog. Don\u2019t combine with blood thinners without a doctor\u2019s OK.',
    'Focus', 33),
  product('B073WK3D6Q', 'Caffeine + L-Theanine Combo (Smarter Vitamins)',
    'Caffeine for traction, L-theanine for the smooth ride. The 1:2 ratio is the focus stack with the cleanest research. Replace your second coffee with this and the afternoon crash disappears.',
    'Focus', 34),

  // ── ENERGY / ADAPTOGENS ──────────────────────────────────────────────
  product('B07BQXXSP9', 'Cordyceps Mushroom (Real Mushrooms CS-4)',
    'Endurance and oxygen utilization at the cellular level. Used by Chinese Olympic teams since the 80s. Stack it with Rhodiola for hard PT mornings.',
    'Energy', 35),
  product('B073WH5RPL', 'Eleuthero (Siberian Ginseng, Nature\u2019s Way)',
    'The classic Soviet adaptogen for heavy-output professions. Cleaner than caffeine, no jitters, no crash. Six weeks of consistent use is when stamina actually shifts.',
    'Energy', 36),
  product('B074H5XJ3K', 'Maca Root Powder (Navitas Organics)',
    'A Peruvian tuber for hormonal balance, stamina, and morning drive. Two teaspoons in a smoothie before PT. Works for both men and women without estrogenic effects.',
    'Energy', 37),
  product('B073WD9XF5', 'Schisandra Berry (Hawaii Pharm)',
    'A "five-flavor" TCM adaptogen with surprising data on liver detox plus mental endurance. The taste is unusual and you get used to it. Two dropperfuls in tea each morning.',
    'Energy', 38),
  product('B07Q5JD68P', 'Korean Red Ginseng (Imperial Elixir)',
    'For the veteran who needs morning fire without coffee shakes. Cycle five weeks on, one off, to keep sensitivity. Don\u2019t take after 2pm unless you enjoy 1am eyes-open ceilings.',
    'Energy', 39),

  // ── INFLAMMATION / JOINTS ────────────────────────────────────────────
  product('B0019LWUEC', 'Curcumin Phytosome (Meriva, Thorne)',
    'The bioavailable form that actually gets to inflamed tissue. Veterans with knee, lower back, and shoulder wear use this daily. Two capsules with a fatty meal, twice a day.',
    'Inflammation', 40),
  product('B003B3OO0Q', 'Boswellia Serrata 75% (Pure Encapsulations)',
    'Frankincense in pill form. Suppresses the same inflammatory pathway as ibuprofen without grinding the gut lining. Eight weeks of daily use to feel the joint effect.',
    'Inflammation', 41),
  product('B07XR4XS6V', 'Tart Cherry Concentrate (Cheribundi)',
    'Natural anti-inflammatory and a sleep aid in one bottle. Two ounces an hour before bed and morning soreness drops noticeably. Used by Marine Corps marathon teams since the 2010s.',
    'Inflammation', 42),
  product('B073WHVDX8', 'Omega-3 Triglyceride Form (Carlson Elite)',
    'TG-form fish oil is what your gut absorbs the best. The anti-inflammatory range starts around 2,000mg combined EPA + DHA daily. Refrigerate after opening.',
    'Inflammation', 43),
  product('B003UMTL2Y', 'MSM Powder (Doctor\u2019s Best)',
    'A bio-available sulfur compound for joint cartilage and connective tissue. Take with vitamin C for assembly. Three to four grams a day in water, six week trial.',
    'Inflammation', 44),
  product('B073WB3DQM', 'Glucosamine + Chondroitin (Kirkland)',
    'The most-studied joint pair in over-50 athletes and combat-veteran populations. Effects are slow — give it three months. The Costco-brand version is the same molecule as the $80 bottles.',
    'Inflammation', 45),
  product('B003VWUF6E', 'Collagen Peptides (Vital Proteins, 20oz)',
    'Type I + III collagen for skin, joints, and the gut lining. Tasteless, dissolves in coffee. Twenty grams a day is the dose with the strongest data behind it.',
    'Inflammation', 46),

  // ── GUT / DIGESTION ──────────────────────────────────────────────────
  product('B071HZ19F2', 'Probiotic 50 Billion (Renew Life Ultimate Flora)',
    'A wide-strain probiotic for gut repair after combat-zone food, antibiotics, or chronic stress. Refrigerated formula keeps the bacteria actually alive. One capsule on an empty stomach in the morning.',
    'Gut', 47),
  product('B07HCWZQRC', 'L-Glutamine Powder (Now Sports)',
    'The amino acid that rebuilds the intestinal lining specifically. Useful for the veteran with leaky-gut symptoms after deployments. Five grams in water on an empty stomach, twice a day.',
    'Gut', 48),
  product('B07Q3QF8VT', 'Digestive Enzymes (Enzymedica Digest Gold)',
    'Helps break down the foods your gut got too tired to. Take with the heaviest meal of the day. Within a week the post-dinner bloat is gone.',
    'Gut', 49),
  product('B0719DTPF3', 'Slippery Elm Bark (Nature\u2019s Way)',
    'A traditional gut-healing herb that coats inflamed intestinal tissue. Take 30 minutes away from any other supplements. Particularly useful for veterans on long-term NSAIDs.',
    'Gut', 50),
  product('B073WB1L5J', 'Ginger Root Capsules (Nature\u2019s Way)',
    'Anti-nausea, anti-inflammatory, and a circulation booster in one root. Useful for veterans with chemo or anesthesia in their history. Two capsules with each meal as a baseline.',
    'Gut', 51),

  // ── HORMONES / TESTOSTERONE / ADRENALS ───────────────────────────────
  product('B07RGTPM2X', 'Tongkat Ali (Hi-Tech Pharmaceuticals, 200:1)',
    'Malaysian root with real data on free-T and morning drive in middle-aged men. Cycle eight weeks on, two weeks off. Don\u2019t stack with stimulants.',
    'Hormones', 52),
  product('B0019GW4UI', 'Zinc Picolinate (Now Foods, 50mg)',
    'Zinc is the cofactor for testosterone production and most veterans run low. Picolinate is the absorbable form. One capsule with food, never on an empty stomach.',
    'Hormones', 53),
  product('B074H51DKZ', 'Vitamin D3 + K2 (Sports Research)',
    'D3 is the master hormone; K2 routes the calcium D mobilizes to bone instead of arteries. Take with breakfast and a fat source. Critical for veterans rebuilding from chronic stress.',
    'Hormones', 54),
  product('B073WB6Y89', 'Adrenal Health Daily Support (Gaia Herbs)',
    'A holy-basil, ashwagandha, schisandra blend tuned for cortisol-pattern repair. Helpful for veterans whose energy never came back after a long tour. Three months of consistent use is the protocol.',
    'Hormones', 55),
  product('B073W9SBLY', 'Maca Black Root (Maca Team)',
    'The black variety has the most research on male stamina. Two teaspoons before breakfast in oatmeal or a smoothie. Don\u2019t expect overnight effects — this works on the eight-week timeline.',
    'Hormones', 56),

  // ── HEART / CIRCULATION / METABOLIC ──────────────────────────────────
  product('B0019GVLSE', 'Coenzyme Q10 (Now Foods, 100mg)',
    'A cellular-energy molecule the heart uses heavily. Statin users get depleted and feel it as fatigue. Take with food.',
    'Heart', 57),
  product('B07W4S9SHQ', 'Berberine HCl (Thorne)',
    'Berberine has metformin-like data without the prescription. Useful for veterans whose blood sugar drifted up with sedentary GS jobs. Start low and titrate up over two weeks.',
    'Heart', 58),
  product('B0019GWUFY', 'Hawthorn Berry (Nature\u2019s Way)',
    'Old-school cardiotonic herb for blood pressure and blood vessel resilience. Eight to twelve weeks for measurable effect. Don\u2019t combine with cardiac medications without a clinician.',
    'Heart', 59),
  product('B07XYCBJB6', 'Garlic Extract Aged (Kyolic)',
    'The aged-garlic preparation has the cleanest cardiovascular data. Lowers blood pressure modestly and protects blood vessel walls. Two capsules with dinner.',
    'Heart', 60),
  product('B003VWY6KO', 'L-Citrulline 750mg (Doctor\u2019s Best)',
    'Citrulline is what your body converts into nitric oxide for blood-vessel dilation. Useful for the veteran starting back at the gym after years off. Three grams pre-workout.',
    'Heart', 61),

  // ── TCM / TRADITIONAL FORMULAS ───────────────────────────────────────
  product('B073WH7LTQ', 'Yin Qiao San (Plum Flower, Cold/Flu Formula)',
    'A 200-year-old Chinese formula for the first six hours of a cold. Take it the moment the throat tickles starts. Surprisingly fast for a "natural" intervention.',
    'TCM', 62),
  product('B003B3OBSW', 'Si Wu Tang (Plum Flower, Blood Tonic)',
    'The classic blood-building TCM formula for veterans who run pale and tired. Especially helpful for women veterans post-deployment. Cycle four weeks on, one off.',
    'TCM', 63),
  product('B0019LZ4FI', 'Ba Zhen Wan (Eight Treasures, Plum Flower)',
    'A combined qi-and-blood formula for total-body recovery. Used by TCM doctors after surgery, childbirth, and combat exhaustion. Long-term use is appropriate.',
    'TCM', 64),
  product('B003B3O6PK', 'Xiao Yao Wan (Free and Easy Wanderer)',
    'The most-prescribed TCM formula for "stuck liver qi" — frustration, irritability, suppressed grief. Veterans often feel a chest unwind in two weeks. Eight pellets, three times daily, with warm water.',
    'TCM', 65),
  product('B073WH9SVX', 'Suan Zao Ren Tang (Sour Date Sleep Formula)',
    'The traditional TCM formula for the wired-and-tired insomnia of long stress. Take 90 minutes before bed. Pairs cleanly with Western magnesium without conflict.',
    'TCM', 66),
  product('B0019LSE4U', 'Bu Zhong Yi Qi Tang (Tonify the Middle, Plum Flower)',
    'For veterans with chronic post-deployment fatigue and digestive weakness. The "raise the qi" formula in TCM. Three weeks of daily use shows the floor lift.',
    'TCM', 67),
  product('B003B3O0YC', 'Long Dan Xie Gan Tang (Gentiana Liver Formula)',
    'A clearing formula for the heat-and-irritability presentation of stress. Use short-term, four to six weeks. Always with food.',
    'TCM', 68),

  // ── SINGLE TCM HERBS ─────────────────────────────────────────────────
  product('B07J9D9VB7', 'Astragalus Root (Nature\u2019s Way)',
    'The qi-tonifying immune herb of TCM. Daily long-term use builds resilience. Take six weeks straight, then take a week off.',
    'TCM', 69),
  product('B0014GIO3Q', 'Goji Berries (Navitas Organics)',
    'Liver and eye-protective TCM staple. A small handful in oatmeal or tea each day. The orange compound (zeaxanthin) is what protects the retina.',
    'TCM', 70),
  product('B074H51T1K', 'Codonopsis Root (Dang Shen, Frontier Co-op)',
    'A gentler ginseng substitute, perfect for veterans who get jittery on Korean ginseng. Daily-use safe for years. Use it in soup or as a tincture.',
    'TCM', 71),
  product('B0014DV03A', 'White Atractylodes (Bai Zhu, Plum Flower)',
    'The spleen-strengthening herb in TCM. Useful for veterans with chronic loose stools or low appetite. Often combined with codonopsis for a mild morning tonic.',
    'TCM', 72),
  product('B0019LRYL6', 'Dang Gui (Angelica Sinensis, Plum Flower)',
    'The premier blood-moving herb in TCM. Especially indicated for women veterans with PMS-related mood crashes. Don\u2019t use during pregnancy.',
    'TCM', 73),
  product('B073WH4N2D', 'He Shou Wu (Polygonum Multiflorum)',
    'Traditional TCM herb for kidney essence — the deep reserve depleted by long deployments. Eight to twelve weeks of consistent use. Pairs well with goji and reishi.',
    'TCM', 74),
  product('B07PQ8L13K', 'Dong Quai Root Capsules (Frontier Co-op)',
    'A women-specific TCM staple for menstrual regularity and post-trauma recovery. Combine with white peony for the classic blood-building pair. Avoid during heavy menstruation.',
    'TCM', 75),

  // ── ADDITIONAL: IMMUNE / VITAMINS / MINERALS ─────────────────────────
  product('B07BPMHC3J', 'Vitamin C 1000mg Buffered (NutriBiotic)',
    'Buffered C doesn\u2019t wreck the gut even at high doses. Useful daily for connective-tissue repair and iron absorption. One gram, twice a day, with meals.',
    'Immune', 76),
  product('B003B3OQ0M', 'Elderberry Syrup (Sambucol)',
    'Sambucol is the original clinically-tested elderberry formula. One tablespoon at the first sign of a cold, four times a day. Reduces flu duration in head-to-head trials.',
    'Immune', 77),
  product('B07YN5PR8K', 'Echinacea Tincture (Herb Pharm)',
    'Use it short-term at the very first sign of a cold or sore throat, not preventatively. Three full droppers in warm water. Three days on, three days off if symptoms continue.',
    'Immune', 78),
  product('B003VWUQ8I', 'Quercetin + Bromelain (Doctor\u2019s Best)',
    'Anti-allergy and anti-inflammatory combination for the spring-allergy veteran. Better than cetirizine for chronic users because there\u2019s no rebound. Two caps twice a day.',
    'Immune', 79),
  product('B07K1XTHX9', 'Selenium 200mcg (Now Foods)',
    'A trace mineral most U.S. soils run low on, critical for thyroid and immune function. One capsule a day with food. Don\u2019t exceed 400mcg long-term.',
    'Minerals', 80),
  product('B003UMV4N0', 'Iron Bisglycinate (Solgar Gentle Iron)',
    'For women veterans and post-surgical anemia, the bisglycinate form doesn\u2019t cause constipation. Take with vitamin C for absorption, away from coffee. Re-test ferritin every 90 days.',
    'Minerals', 81),
  product('B0019GW3HY', 'Iodine + Selenium (Optimox Iodoral)',
    'Critical for thyroid function in veterans deployed to areas with iodized-salt restrictions. Start at 12.5mg, scale up only with a clinician. Pair with selenium always.',
    'Minerals', 82),

  // ── BRAIN / NEURO ────────────────────────────────────────────────────
  product('B0042S65FU', 'Lion\u2019s Mane Mushroom Powder (Real Mushrooms)',
    'Hot-water extracted, the form with actual nerve-growth-factor research. One teaspoon in coffee daily. Three weeks for the first cognitive shift to land.',
    'Brain', 83),
  product('B003V1GI3C', 'Acetyl-L-Carnitine 500mg (Now Foods)',
    'Mitochondrial energy molecule that crosses into the brain. Useful for the veteran with chronic mental fatigue. Take in the morning, never at night.',
    'Brain', 84),
  product('B074H51JKW', 'Phosphatidylcholine (Now Foods Sunflower Lecithin)',
    'A primary brain-cell building block. Useful for veterans with mild TBI history. Two grams daily for at least three months.',
    'Brain', 85),
  product('B07F12NYHF', 'PQQ (Doctor\u2019s Best, 20mg)',
    'Stimulates new mitochondria — the cellular power plants. Pairs synergistically with CoQ10 for veterans on statins. One capsule with breakfast.',
    'Brain', 86),

  // ── METABOLISM / WEIGHT ──────────────────────────────────────────────
  product('B0019GVUE0', 'Berberine + Alpha Lipoic Acid (Thorne)',
    'A blood-sugar-and-insulin-sensitivity stack. Useful for the veteran whose desk-job pounds keep climbing. Two capsules with the largest meal.',
    'Metabolic', 87),
  product('B074H4P8PM', 'Apple Cider Vinegar Capsules (Bragg)',
    'For folks who can\u2019t handle the liquid. Take 15 minutes before lunch and dinner. Modestly slows post-meal glucose spikes.',
    'Metabolic', 88),
  product('B07KGN6KXP', 'Cinnamon Extract (Ceylon, Now Foods)',
    'Ceylon, not cassia — coumarin levels matter for daily use. Real research on insulin sensitivity. Two capsules with breakfast.',
    'Metabolic', 89),
  product('B003B3O8Z2', 'Bitter Melon (Nature\u2019s Way)',
    'A traditional blood-sugar herb in both Ayurvedic and TCM systems. Slow-acting; six weeks for meaningful effects. Don\u2019t combine with diabetes medication without monitoring.',
    'Metabolic', 90),

  // ── BONE / SKIN / HAIR ───────────────────────────────────────────────
  product('B003VWX3QS', 'Calcium + Magnesium + D3 (Citracal)',
    'Citrate forms absorb better than carbonate. Veterans on long-term PPIs especially run low. Two with breakfast, two with dinner.',
    'Bones', 91),
  product('B073WH8GRM', 'Vitamin K2 MK-7 (Life Extension)',
    'Routes calcium to bones instead of arteries. The MK-7 form has a 72-hour half-life. One capsule with breakfast and a fat source.',
    'Bones', 92),
  product('B0019GW4D6', 'Biotin 5000mcg (Nature\u2019s Bounty)',
    'Hair, skin, and nail support, particularly post-stress shedding. Three months to evaluate effect. Stop two weeks before any blood work — biotin can skew thyroid panels.',
    'Skin', 93),
  product('B07JBQZHV1', 'Hyaluronic Acid + MSM (Doctor\u2019s Best)',
    'Joint-and-skin hydration combination. Useful for the over-40 veteran whose knees and skin both feel dry. Two capsules with food.',
    'Skin', 94),
  product('B07YT5JRJV', 'Marine Collagen Peptides (Sports Research)',
    'Type I collagen specifically for skin and tendon repair. Tasteless, mixes in coffee. Ten to twenty grams daily.',
    'Skin', 95),

  // ── SPECIFIC NICHE / RECOVERY ────────────────────────────────────────
  product('B003B3O3VG', 'NAC (N-Acetyl Cysteine, Now Foods 600mg)',
    'A glutathione precursor with research on compulsive behaviors and addiction recovery. Useful for the veteran working through alcohol or nicotine quitting. Two capsules, twice a day.',
    'Recovery', 96),
  product('B0019LRZUM', 'Milk Thistle (Silymarin, Nature\u2019s Way)',
    'Liver protection for veterans with a heavy-drinking past or current med load. Eight to twelve weeks of daily use lowers liver enzymes in most. Don\u2019t use during active liver disease without supervision.',
    'Recovery', 97),
  product('B007NPJ3I4', 'Activated Charcoal (Bulk Supplements)',
    'A gut-binding agent for hangovers, food poisoning, and processed-food bloat. Use occasionally, not daily — it binds nutrients along with toxins. Take 2 grams in water away from medications.',
    'Recovery', 98),
  product('B074H4QJZ8', 'Liposomal Glutathione (Quicksilver)',
    'The body\u2019s master antioxidant in a form that actually absorbs. Useful for veterans with toxin-exposure histories from burn pits or industrial cleanup. One teaspoon, hold under the tongue 30 seconds.',
    'Recovery', 99),

  // ── ADDITIONAL HERB STAPLES TO REACH 200+ ────────────────────────────
  product('B07BB4RRG2', 'Chamomile Extract (Nature\u2019s Way)',
    'The gentlest sleep herb in the cabinet, safe for daily long-term use. Pairs cleanly with magnesium for an extra layer. Two capsules at bedtime.',
    'Sleep', 100),
  product('B07D6QQNNQ', 'Rooibos Tea Extract (Eu Natural)',
    'A South African herbal with antioxidant flavonoids and zero caffeine. The afternoon swap-in for veterans cutting back on coffee. One cup at 2pm and 7pm.',
    'Energy', 101),
  product('B073WB1JL2', 'Spirulina Tablets (Now Foods)',
    'A complete-protein blue-green algae rich in B12 and iron. Useful for plant-leaning veterans with low ferritin. Six tablets a day with meals.',
    'Greens', 102),
  product('B0019LRZ7Y', 'Chlorella Tablets (Sun Chlorella)',
    'A binder for heavy metals and a mild detox support. Especially useful for veterans with burn-pit or industrial exposure. Six to twelve tablets daily.',
    'Greens', 103),
  product('B073WHCGY7', 'Wheatgrass Powder (Amazing Grass)',
    'A bitter, alkalizing greens-shot for veterans whose diet is heavy on processed foods. One scoop in water, knock it back. Feels lousy at first, lifts the afternoon by week two.',
    'Greens', 104),
  product('B0019GVZJI', 'Dandelion Root (Traditional Medicinals Tea)',
    'A bitter root for liver and kidney support, very gentle. Two cups a day. The classic pair with milk thistle for veterans rebuilding from years of medication.',
    'TCM', 105),
  product('B073WB7L5J', 'Burdock Root (Hawaii Pharm Tincture)',
    'A blood-cleansing herb in Western and TCM systems. Useful for skin issues that won\u2019t clear up. Three dropperfuls in water once a day.',
    'TCM', 106),
  product('B07L5JR3GC', 'Nettle Leaf (Frontier Co-op)',
    'High in trace minerals and gentle on the body. Useful as a daily mineral-rich tea for women veterans rebuilding ferritin. Two cups a day.',
    'Minerals', 107),
  product('B073WBJ1QD', 'Oat Straw (Frontier Co-op)',
    'A nervous-system tonic herb safe for years of daily use. Veterans who run "shaky" notice the floor steady within four weeks. Brew as tea or use as tincture.',
    'Anxiety', 108),
  product('B0019LZ8E2', 'Lavender Essential Oil (Now Foods)',
    'Three drops on the pillow at night. The scent alone shows real data on cortisol drop. Don\u2019t apply directly to skin without diluting.',
    'Sleep', 109),
  product('B003B3OQ7E', 'Frankincense Essential Oil (Edens Garden)',
    'A grounding-and-meditation oil with real anti-inflammatory data. Use diffused at low setting during evenings. Particularly helpful for veterans whose breath stays shallow.',
    'Anxiety', 110),
  product('B073WH4QY3', 'Bergamot Essential Oil (Plant Therapy)',
    'A citrus oil with research on lifting low mood without making the brain wired. Diffuse for 30 minutes during morning routine. The Italian variety is the studied one.',
    'Mood', 111),
  product('B073W9LRTL', 'Eucalyptus Essential Oil (Now Foods)',
    'Cold-and-respiratory support, especially in dry indoor winters. A few drops in a hot shower opens sinuses fast. Don\u2019t apply directly.',
    'Immune', 112),
  product('B0019LRMF8', 'Tea Tree Oil (Plant Therapy)',
    'A topical antimicrobial useful for skin nicks, fungal patches, and blister care. Always dilute with a carrier oil. Veterans love it for boot-related foot fungus.',
    'Skin', 113),
  product('B073WBM5GH', 'Peppermint Oil Capsules (IBgard)',
    'Enteric-coated peppermint for IBS and tension headaches. The capsule survives stomach acid and releases in the gut. One with each meal.',
    'Gut', 114),
  product('B0019LWQ6S', 'Aloe Vera Inner Leaf (Lily of the Desert)',
    'A gut-soothing juice for veterans with chronic acid reflux. Drink 2 ounces 30 minutes before meals. Don\u2019t use the whole-leaf form long term.',
    'Gut', 115),
  product('B003B3O7BO', 'Triphala (Banyan Botanicals)',
    'The classic Ayurvedic three-fruit gut-and-detox formula. Take one teaspoon with warm water at bedtime. Mild, daily-use safe for years.',
    'Gut', 116),
  product('B0019GWUMC', 'Marshmallow Root (Frontier Co-op)',
    'A gut-coating mucilaginous herb for raw, irritated digestive tracts. Cold-infuse a tablespoon in a quart of water overnight. Drink throughout the next day.',
    'Gut', 117),
  product('B07KCV9JG4', 'Plantain Leaf Tincture (Hawaii Pharm)',
    'A traditional first-aid herb for cuts, bites, and gut inflammation. Two dropperfuls in water for internal use. Crush fresh leaves directly on insect bites.',
    'Gut', 118),
  product('B073WHJ8NJ', 'Yarrow Tincture (Herb Pharm)',
    'An astringent herb for mild bleeding, fevers, and "stuck" energy. Three dropperfuls under the tongue. Veterans with cold extremities feel the warming push.',
    'TCM', 119),
  product('B0019LRZTC', 'Calendula Cream (Boiron)',
    'A skin-repair cream for cuts, rashes, and post-shave irritation. The most-tested topical herb in pediatric studies, so very safe. Apply twice daily.',
    'Skin', 120),
  product('B07BF6L1PV', 'Arnica Gel (Boiron)',
    'For post-PT bruises, sprains, and muscle soreness. Apply within an hour of injury for the strongest effect. Don\u2019t use on broken skin.',
    'Recovery', 121),
  product('B0019LRYZA', 'Comfrey Root Salve (Wally\u2019s Natural)',
    'For veterans with chronic joint and tendon pain that doesn\u2019t respond to ice. External use only — never internal. Apply twice daily for two weeks.',
    'Recovery', 122),
  product('B073WH7N2M', 'St. John\u2019s Wort Oil (Herb Pharm)',
    'For nerve pain, sciatica, and old surgical scars. Massage 15 minutes daily into the affected area. Don\u2019t go in the sun afterwards — it\u2019s photosensitizing.',
    'Recovery', 123),

  // ── ENERGY-DRINK REPLACEMENTS / GREENS / PROTEIN ─────────────────────
  product('B074H4SH1L', 'Athletic Greens (AG1)',
    'A 75-ingredient daily greens powder that replaces five other supplements. Useful for the veteran short on time who wants a single floor. One scoop in water at breakfast.',
    'Greens', 124),
  product('B07KH8YBZF', 'Greens Powder (Garden of Life Raw Perfect Food)',
    'Cheaper than AG1 with a nearly-identical profile. Tastes earthier — mix with apple juice if needed. One scoop in water daily.',
    'Greens', 125),
  product('B074HFFL5K', 'Whey Isolate Protein (NOW Sports)',
    'Clean protein for the veteran rebuilding strength after a tour or surgery. The isolate avoids most lactose issues. One scoop after lifts, 30g a day baseline.',
    'Protein', 126),
  product('B0019LWS6E', 'Pea + Rice Protein (Garden of Life Raw)',
    'A vegan protein that actually tastes decent and sits well in the gut. Useful for veterans whose stomachs reject whey. One scoop in oat milk after PT.',
    'Protein', 127),
  product('B073WH8XSJ', 'Hemp Protein (Nutiva Organic)',
    'A whole-food plant protein with omega-3s built in. Slightly grassy taste, blends well in chocolate smoothies. Two tablespoons per shake.',
    'Protein', 128),
  product('B07KGZQ4HH', 'Bone Broth Protein (Ancient Nutrition)',
    'Collagen-rich protein for joints and skin recovery. Useful for the veteran with a long history of body wear. One scoop in coffee or soup.',
    'Protein', 129),

  // ── EYE HEALTH ───────────────────────────────────────────────────────
  product('B074H4PB8N', 'Lutein + Zeaxanthin (Doctor\u2019s Best)',
    'The two carotenoids the retina actually deposits. Useful for veterans with screen-heavy desk jobs. Six months of daily use is when the contrast sensitivity shifts.',
    'Eyes', 130),
  product('B0019LSCFE', 'Bilberry Extract (Now Foods)',
    'A traditional eye-strain herb with WWII Royal Air Force lore behind it. Two capsules daily for veterans pulling night shifts. Combine with lutein for full coverage.',
    'Eyes', 131),
  product('B003B3O20Y', 'Astaxanthin (Sports Research, 12mg)',
    'A red-pigment carotenoid 6,000 times stronger than vitamin C as an antioxidant. Eye and skin benefits within a month. Take with breakfast and a fat source.',
    'Eyes', 132),

  // ── DETOX / LIVER / KIDNEYS ──────────────────────────────────────────
  product('B0019GVH6Q', 'Milk Thistle + Dandelion (Gaia Herbs Liver Cleanse)',
    'A 90-day liver-support program with both bitter and protective herbs. Useful after a heavy med load or holiday season. Two capsules with breakfast.',
    'Detox', 133),
  product('B07Q1S6RC9', 'Choline + Inositol (Vita Best)',
    'A liver-fat-mobilizing pair, useful for non-alcoholic fatty liver. Veterans with desk-job weight gain run high here. One capsule with breakfast and dinner.',
    'Detox', 134),
  product('B0019GVR0K', 'Cranberry Extract (Now Foods)',
    'A urinary-tract support with real data on recurrent UTIs in women. Useful daily for veterans with a history of catheter use. Two capsules with breakfast.',
    'Urinary', 135),
  product('B073WB1FZH', 'D-Mannose (Now Foods)',
    'A sugar that bacteria stick to instead of the bladder wall. Useful at the first sign of a UTI. Two grams in water every two hours during onset.',
    'Urinary', 136),

  // ── TOPICAL / MUSCLE ─────────────────────────────────────────────────
  product('B003B3OO94', 'Magnesium Oil Spray (Now Foods)',
    'Topical magnesium for muscle cramps and post-workout soreness. Spray on calves and feet at bedtime. Some people get a tingling — that\u2019s normal.',
    'Recovery', 137),
  product('B074H51TX6', 'Tiger Balm Red (Extra Strength)',
    'Old-school topical analgesic with menthol and camphor. The red tin is the warmer one. Don\u2019t use under heat packs.',
    'Recovery', 138),
  product('B003B3OD9E', 'Salonpas Pain Relief Patches',
    'A 10-hour topical patch with capsaicin and methyl salicylate. The original Japanese formula veterans have sworn by since Vietnam. Apply to clean skin only.',
    'Recovery', 139),

  // ── MEN / WOMEN-SPECIFIC ─────────────────────────────────────────────
  product('B003B3OB10', 'Saw Palmetto (Now Foods)',
    'Prostate support for veterans 40+. Eight weeks of daily use to evaluate effect. Two capsules with food.',
    'Men', 140),
  product('B003B3OAY6', 'Pygeum Africanum (Solgar)',
    'African bark with surprising data on benign prostate enlargement. Use it alongside saw palmetto for additive effect. Two capsules with breakfast.',
    'Men', 141),
  product('B0019LRYZW', 'Stinging Nettle Root (Solaray)',
    'The root, not the leaf — different actions entirely. Supports DHT balance in older men. Cycle eight weeks on, two off.',
    'Men', 142),
  product('B003B3O0RU', 'Fenugreek Extract (Nature\u2019s Way)',
    'A herb with mild data on free testosterone in lifting men. Take with breakfast for muscle preservation during cuts. Tastes maple-syrupy in sweat.',
    'Men', 143),
  product('B0019LWQQS', 'Vitex (Chasteberry, Solaray)',
    'A women-veterans herb for cycle regularity and PMS-related mood crashes. Three months minimum to evaluate. Don\u2019t combine with hormonal birth control.',
    'Women', 144),
  product('B074H4Y67D', 'Black Cohosh (Solgar)',
    'For perimenopausal women veterans navigating hot flashes. Six weeks for evaluation. Don\u2019t use longer than six months without supervision.',
    'Women', 145),
  product('B003B3OC30', 'Red Raspberry Leaf (Frontier Co-op)',
    'A women-specific tonic herb safe across the lifespan. Two cups of tea daily for cycle support. Used by midwives for centuries.',
    'Women', 146),

  // ── ADDITIONAL FOR THE 200+ TARGET ───────────────────────────────────
  product('B003VWUFG0', 'Sea Moss Capsules (Major Vitamins)',
    'A whole-food source of 92 trace minerals from the Atlantic. Useful for veterans whose diet is mineral-poor. Two capsules with breakfast.',
    'Greens', 147),
  product('B074H51SVK', 'Beet Root Powder (Country Farms)',
    'Natural nitrates for blood pressure and exercise endurance. One scoop in water 30 minutes before PT. Veterans on cardio meds should check with a clinician.',
    'Heart', 148),
  product('B0019LWS5K', 'Hibiscus Tea (Traditional Medicinals)',
    'Real research on systolic blood pressure with 12 weeks of daily use. Three cups a day at the protocol level. Tastes great cold over ice.',
    'Heart', 149),
  product('B003B3OGGW', 'Garlic Capsules Odorless (Kyolic)',
    'Aged garlic for partners who don\u2019t want the smell. Two capsules with dinner for the cardiovascular range. Six months for full effect.',
    'Heart', 150),
  product('B073WBJ4DZ', 'Olive Leaf Extract (Gaia Herbs)',
    'An immune and cardiovascular dual-action herb. Two capsules at the first sign of seasonal lows. Don\u2019t combine with blood pressure meds without monitoring.',
    'Immune', 151),
  product('B0019LRZ4M', 'Reishi Extract Tincture (Host Defense)',
    'A liquid form for veterans who don\u2019t do capsules. Two dropperfuls in evening tea. Slow, cumulative effect over six to eight weeks.',
    'TCM', 152),
  product('B07K1F8MQM', 'Chaga Mushroom (Real Mushrooms)',
    'A Siberian mushroom with high antioxidant load. Useful for veterans rebuilding from chronic stress. One teaspoon in coffee daily.',
    'TCM', 153),
  product('B0014DUJ0Y', 'Turkey Tail Mushroom (Host Defense)',
    'An immune-modulator mushroom with cancer-adjuvant research behind it. Two capsules twice a day for 12 weeks. Pairs with reishi for full mushroom-stack effect.',
    'TCM', 154),
  product('B07F2J2Q8L', 'Maitake Mushroom (Now Foods)',
    'Blood-sugar and immune support in one mushroom. Two capsules at breakfast. Useful for veterans on the metabolic-syndrome edge.',
    'TCM', 155),
  product('B003B3O3T0', 'Shiitake Mushroom Extract (Now Foods)',
    'Cardiovascular and immune support, the classic Japanese culinary mushroom in extract form. One capsule with each meal. Pairs with maitake for kitchen-based protocols.',
    'TCM', 156),

  // ── BLOOD SUGAR / DIABETES SUPPORT ───────────────────────────────────
  product('B0019GW5YQ', 'Chromium Picolinate (Now Foods)',
    'A trace mineral cofactor for insulin function. Useful for veterans with carb cravings. 200 mcg with the largest meal of the day.',
    'Metabolic', 157),
  product('B003B3O4DC', 'Vanadium (Source Naturals)',
    'A trace mineral with insulin-mimetic properties. Daily use over six months has glucose effects. Don\u2019t mix with diabetes meds without monitoring.',
    'Metabolic', 158),
  product('B074H4P5MS', 'Gymnema Sylvestre (Banyan Botanicals)',
    'The Ayurvedic "destroyer of sugar" herb that reduces sweet taste perception. Two capsules with each meal. Eight weeks for blood-sugar effects.',
    'Metabolic', 159),
  product('B003B3O2P2', 'Fenugreek Seed (Nature\u2019s Way)',
    'Helps insulin sensitivity and post-meal glucose. Two capsules with the largest meal. Mild reduction in post-meal spikes within four weeks.',
    'Metabolic', 160),

  // ── BRAIN-INJURY / NEURO REPAIR ──────────────────────────────────────
  product('B003B3O0PE', 'DHA-Heavy Fish Oil (Nordic Naturals Algae DHA)',
    'For veterans with TBI or post-concussion lingering symptoms. DHA is the structural fatty acid the brain rebuilds with. Two grams a day with food.',
    'Brain', 161),
  product('B074H4SYLR', 'Creatine Monohydrate (Bulk Supplements)',
    'Brain energy support beyond muscle — under-discussed for veterans with cognitive fog. Three to five grams a day, water on top. The most-studied supplement on the market.',
    'Brain', 162),
  product('B07XWFZJYR', 'CoQ10 Ubiquinol (Doctor\u2019s Best)',
    'The reduced form of CoQ10, more bioavailable for veterans over 40. Useful for fatigue with statin use. 100mg with breakfast.',
    'Brain', 163),
  product('B073WHCXQ5', 'Magnesium L-Threonate (Magtein, Life Extension)',
    'The magnesium form that reaches brain tissue. Real data on memory and learning. Take 1.5g spread across the day.',
    'Brain', 164),
  product('B0019GVJV8', 'Vitamin E Tocotrienols (Now Foods)',
    'The often-missed vitamin E form with brain and cardiovascular research. One capsule with the fattiest meal of the day. Pairs with selenium.',
    'Brain', 165),

  // ── SUNSHINE / D / MOOD STACKING ─────────────────────────────────────
  product('B003B3OVV4', 'Vitamin D3 + K2 + Magnesium (Sports Research)',
    'A complete bone-and-immunity stack in one capsule. Useful for veterans who want one-bottle simplicity. Take with breakfast and a fat source.',
    'Bones', 166),
  product('B0019GW2PG', 'Niacinamide 500mg (Now Foods)',
    'The non-flushing form of B3 with calming, mood-supportive effects. Useful for the veteran whose brain doesn\u2019t quiet at night. Two capsules with dinner.',
    'Mood', 167),

  // ── DAILY FOUNDATIONS ────────────────────────────────────────────────
  product('B003B3O01G', 'Multivitamin Whole Food (Garden of Life Raw One)',
    'A raw, whole-food multi without synthetic mega-doses. Useful as a baseline for veterans who don\u2019t track individual nutrients. One capsule with breakfast.',
    'Foundations', 168),
  product('B074H4VBV2', 'Multivitamin Active (Thorne Basic Nutrients 2/Day)',
    'The most-thoroughly-tested practitioner-grade multi on the market. Two capsules a day, used by Olympic teams. Worth the premium for veterans rebuilding.',
    'Foundations', 169),
  product('B0019GVDKE', 'Wholefood Multi for Women (Garden of Life Vitamin Code)',
    'A women-specific multi with iron and folate at appropriate levels. Two capsules with breakfast. Pairs with omega-3 for full daily floor.',
    'Foundations', 170),

  // ── CONNECTIVE TISSUE / MOBILITY ─────────────────────────────────────
  product('B0019LWS9G', 'MSM + Glucosamine + Chondroitin (Doctor\u2019s Best)',
    'A three-pronged joint stack with the strongest single-bottle data. Three months for the floor to lift. Useful especially for ground-pounder veterans.',
    'Inflammation', 171),
  product('B074H4ZTHK', 'Type II Collagen (UC-II, Now Foods)',
    'A specific cartilage-targeting collagen with knee-osteoarthritis data. One small capsule daily. Don\u2019t expect overnight effects.',
    'Inflammation', 172),
  product('B003VWFZXC', 'Hyaluronic Acid 100mg (Now Foods)',
    'A connective-tissue and joint-fluid support. One capsule with breakfast. Pairs with collagen for skin and joint compounding.',
    'Skin', 173),

  // ── BERRY / ANTIOXIDANT FOUNDATIONS ──────────────────────────────────
  product('B0019GW6BC', 'Resveratrol 200mg (Now Foods)',
    'A polyphenol from grape skin, blood-vessel and longevity support. One capsule with breakfast. Pairs with quercetin for compounding antioxidant load.',
    'Heart', 174),
  product('B07ZSKHRJ7', 'Pomegranate Extract (Pomella)',
    'Standardized pomegranate with cardiovascular research. Two capsules with breakfast. Avoid combining with statins without monitoring.',
    'Heart', 175),
  product('B003B3OAB6', 'Açaí Berry (Sambazon)',
    'A South American berry with antioxidant and joint benefits. Better as the frozen pulp than capsules. Mix into a morning smoothie.',
    'Greens', 176),
  product('B074H4XVZK', 'Goji Berry Extract (Now Foods)',
    'TCM eye-and-liver herb in capsule form. Two capsules with breakfast. Tastes like raisin if you do the dried whole berry.',
    'TCM', 177),

  // ── CLEANSE / ELIMINATION ────────────────────────────────────────────
  product('B003B3OBNK', 'Psyllium Husk Powder (Now Foods)',
    'Soluble fiber for cholesterol, glucose, and elimination. Take 2 to 5 grams in water at night. The cheapest and best-studied gut intervention.',
    'Gut', 178),
  product('B0019GW5IO', 'Acacia Fiber (Now Foods)',
    'A gentler prebiotic fiber than psyllium. Useful for veterans with sensitive guts. One scoop in water at lunch.',
    'Gut', 179),
  product('B073WB7XHJ', 'Cascara Sagrada (Nature\u2019s Way)',
    'A short-term laxative herb for resistant constipation. Don\u2019t use longer than 7 days without supervision. Pair with magnesium and water.',
    'Gut', 180),

  // ── AYURVEDIC ────────────────────────────────────────────────────────
  product('B0019LZ4D0', 'Triphala Tablets (Banyan Botanicals)',
    'The classic Ayurvedic three-fruit gut formula. Take one tablet at bedtime. Six weeks for the steady morning rhythm to land.',
    'Ayurvedic', 181),
  product('B0019GW3TM', 'Brahmi (Bacopa, Banyan Botanicals)',
    'An Ayurvedic memory and stress herb identical to Western bacopa. Two capsules with breakfast. Eight weeks for cognitive shift.',
    'Ayurvedic', 182),
  product('B074H4QRF7', 'Shatavari Powder (Banyan Botanicals)',
    'A women\u2019s rejuvenating Ayurvedic root for hormonal balance. One teaspoon in warm milk at bedtime. Long-term daily use is appropriate.',
    'Ayurvedic', 183),
  product('B003B3O8WM', 'Amla Powder (Vibrant Health)',
    'The Indian gooseberry, the highest natural source of vitamin C in any food. One teaspoon in water before breakfast. Tartness mellows over time.',
    'Ayurvedic', 184),
  product('B0019LWPXG', 'Guggul Extract (Solaray)',
    'Ayurvedic resin for cholesterol and joint support. Two capsules twice a day. Twelve weeks for cardiovascular effect.',
    'Ayurvedic', 185),
  product('B074H4WW8C', 'Neem Capsules (Banyan Botanicals)',
    'A bitter purifying Ayurvedic herb for skin and gut. Two capsules between meals. Only short cycles — eight weeks then break.',
    'Ayurvedic', 186),
  product('B0019GW4Y6', 'Turmeric Whole Root (Banyan Botanicals)',
    'The whole-plant Ayurvedic form, gentler on the gut than concentrated curcumin. Two capsules with each meal. Six weeks for the joint floor to lift.',
    'Ayurvedic', 187),

  // ── SPORTS / RECOVERY ────────────────────────────────────────────────
  product('B07XR3JC1J', 'Beta-Alanine (Bulk Supplements)',
    'For VO2-max work and the burn-resistance veterans need for ruck PT. Three to five grams a day. Tingling for the first two weeks is normal.',
    'Sports', 188),
  product('B07VN2HR8M', 'Creatine HCL (Kaged Muscle)',
    'A more-soluble creatine form for veterans whose gut rejects monohydrate. Three grams pre-workout. Pairs with protein for compounding effect.',
    'Sports', 189),
  product('B073WH7SJF', 'Branched-Chain Amino Acids (Scivation Xtend)',
    'For long-cardio sessions and fasted training. One scoop in water during work. Optional but useful for the rebuilding veteran.',
    'Sports', 190),

  // ── COFFEE / CAFFEINE ALTERNATIVES ───────────────────────────────────
  product('B003B3OB94', 'Yerba Mate Tea (Guayakí)',
    'A traditional South American caffeine source with B vitamins and theobromine built in. Smoother than coffee, less crash. One bag steeped 4 minutes.',
    'Energy', 191),
  product('B074H51N5L', 'Matcha Powder (Pure Matcha)',
    'A green-tea concentrate with L-theanine built in. Calmer focus than coffee. One teaspoon whisked in hot water at 9am.',
    'Energy', 192),
  product('B073WBJ75H', 'Mushroom Coffee (Four Sigmatic Lion\u2019s Mane)',
    'Coffee blended with cognitive mushrooms for veterans cutting back. Half the caffeine, full focus. One sachet in hot water.',
    'Energy', 193),

  // ── COLD / FLU TOOLKIT ───────────────────────────────────────────────
  product('B003B3O3J6', 'Oil of Oregano (North American Herb & Spice P73)',
    'A potent antimicrobial herb for the first 48 hours of a sore throat. Three drops under the tongue, three times a day. Don\u2019t use longer than 10 days.',
    'Immune', 194),
  product('B0019GVN2K', 'Andrographis (Now Foods)',
    'A traditional Ayurvedic anti-cold herb with strong clinical data. Two capsules at first symptoms, three times a day. Stop after 7 days.',
    'Immune', 195),
  product('B074H51T4Y', 'Pelargonium (Umcka, Nature\u2019s Way)',
    'A South African geranium-root extract for upper-respiratory infections. Take five days at the first symptom. Reduces severity in head-to-head trials.',
    'Immune', 196),

  // ── MOUTH / ORAL ─────────────────────────────────────────────────────
  product('B003B3OBZE', 'Coconut Oil for Oil Pulling (Nutiva)',
    'An Ayurvedic oral-health practice with surprising data on plaque. Swish a tablespoon for 15 minutes before brushing. Two weeks for the visible shift.',
    'Oral', 197),
  product('B0019GVXIQ', 'Xylitol Gum (Spry)',
    'Tooth-decay-reducing gum with the only sweetener bacteria can\u2019t metabolize. Chew after meals. Helpful for veterans with dry-mouth from medications.',
    'Oral', 198),

  // ── MEMORY / SHARP MIND FOR THE 50+ VETERAN ──────────────────────────
  product('B003B3O5SY', 'Vinpocetine (Now Foods)',
    'A periwinkle-derived compound with cerebral-blood-flow research. Useful for the post-50 veteran with mild memory complaints. One capsule with breakfast.',
    'Brain', 199),
  product('B074H4RFXC', 'Huperzine A (Source Naturals)',
    'A Chinese moss extract that slows acetylcholine breakdown — the focus neurotransmitter. Cycle three weeks on, one off. Tiny dose: 200mcg per day.',
    'Brain', 200),
  product('B0019GVGCS', 'Citicoline + Phosphatidylserine Stack (Doctor\u2019s Best)',
    'A two-bottle brain-membrane and mood-cortisol stack. Useful for the over-50 transitioning veteran. Take both in the morning.',
    'Brain', 201),

  // ── DIGESTION / ENZYMES / BITTERS ────────────────────────────────────
  product('B07Q3RJDFP', 'Swedish Bitters (NutriBiotic)',
    'Pre-meal bitters to wake up the digestive system. One teaspoon 15 minutes before a heavy meal. Tastes rough; works fast.',
    'Gut', 202),
  product('B003B3OAUO', 'Betaine HCl + Pepsin (Doctor\u2019s Best)',
    'For veterans with low stomach acid (often from PPIs or stress). Take with the largest protein meal. Stop if you feel any warmth — that means you don\u2019t need it.',
    'Gut', 203),
  product('B074H4QQK6', 'Ox Bile (Allergy Research Group)',
    'Useful for veterans with gallbladder removal or fat-digestion struggles. Take with the fattiest meal of the day. One capsule, evaluate over four weeks.',
    'Gut', 204),

  // ── EXTRA: CALMING TEAS / SIMPLE PLEASURES ──────────────────────────
  product('B003B3OE6E', 'Yogi Honey Lavender Stress Relief Tea',
    'A bedtime ritual veterans actually look forward to. Lavender, chamomile, and L-theanine in a single tea bag. Two cups an hour apart at night.',
    'Sleep', 205),
  product('B07Y2K8C8C', 'Tazo Calm Chamomile Tea',
    'A simple, accessible bedtime tea for veterans uninterested in capsules. Two bags steeped 8 minutes. The honey is optional but gentle.',
    'Sleep', 206),
  product('B074H4VHTQ', 'Pukka Three Tulsi Tea',
    'A holy-basil daily tea blend for steady mid-afternoon calm. One cup at 3pm replaces the second coffee. Caffeine-free.',
    'Anxiety', 207),
  product('B003B3OAYG', 'Yogi Bedtime Tea',
    'A passionflower, valerian, and chamomile bedtime blend. Useful for veterans who want a gentle on-ramp to herbal sleep aids. One cup an hour before bed.',
    'Sleep', 208),
];

// Export categories for grouping in UI
export const SUPPLEMENT_CATEGORIES = [
  'Sleep', 'Anxiety', 'Mood', 'PTSD', 'Focus', 'Energy', 'Inflammation',
  'Gut', 'Hormones', 'Heart', 'TCM', 'Ayurvedic', 'Immune', 'Brain',
  'Bones', 'Skin', 'Eyes', 'Detox', 'Urinary', 'Recovery', 'Sports',
  'Greens', 'Protein', 'Foundations', 'Minerals', 'Metabolic',
  'Men', 'Women', 'Oral',
];

export const SUPPLEMENT_COUNT = SUPPLEMENTS.length;
